@echo off
REM ============================================
REM AWS EC2 QuorumStop - Configuration
REM Generated by setup-wizard.bat on Sat 08/09/2025 15:51:11.12
REM ============================================

REM AWS Configuration
set INSTANCE_ID=i-0500361335200bff5
set AWS_REGION=us-west-2

REM Server Connection (Dynamic)
set SERVER_IP=0.0.0.0
set KEY_FILE=C:\Users\Obad\Downloads\chatable_aws_key.pem

REM Team Count
set TEAM_COUNT=3

REM Team IP Mappings and Names
set DEV1_IP=202.47.38.169
set DEV1_NAME=Obad
set DEV2_IP=202.47.51.161
set DEV2_NAME=Hamza
set DEV3_IP=202.47.36.187
set DEV3_NAME=Dev3

REM Current User Configuration
set YOUR_NAME=Obad
set YOUR_IP=202.47.38.169

REM Server Configuration
set SERVER_VOTE_SCRIPT=/home/ubuntu/vote_shutdown.sh
set SERVER_USER=ubuntu

REM Display Configuration (lists team entries)
if "%1"=="show" (
  echo ============================================
  echo AWS EC2 QuorumStop - Configuration
  echo ============================================
  echo Instance ID: %INSTANCE_ID%
  echo Region: %AWS_REGION%
  echo Server IP: %SERVER_IP%
  echo SSH Key: %KEY_FILE%
  echo User: %SERVER_USER%
  echo.
  echo Team Entries:
  for /L %%n in (1,1,%TEAM_COUNT%) do (
    call echo     DEV%%n_IP=%DEV%%n_IP% (%DEV%%n_NAME%)
  )
  echo.
  echo Current User: %YOUR_NAME% (%YOUR_IP%)
)
