@echo off
setlocal enabledelayedexpansion
echo ============================================
echo AWS EC2 QuorumStop - Setup Wizard
echo ============================================
echo This wizard will create or update scripts\config.bat
echo Press Ctrl+C at any time to abort.
echo.
set "SCRIPT_DIR=%~dp0..\scripts\"
if not exist "%SCRIPT_DIR%" (
  echo ERROR: scripts directory not found at %SCRIPT_DIR%
  exit /b 1
)
set "CONFIG_FILE=%SCRIPT_DIR%config.bat"

set "AWS_PAGER="
aws --version >nul 2>&1
if errorlevel 1 (
  echo WARNING: AWS CLI not detected. You can proceed but testing will fail.
) else (
  for /f "tokens=2 delims=/ " %%v in ('aws --version 2^>nul') do set AWS_CLI_VER=%%v
  echo Detected AWS CLI version: %AWS_CLI_VER%
)
echo.

if exist "%CONFIG_FILE%" (
  echo Existing config.bat detected. A backup will be created.
  copy /y "%CONFIG_FILE%" "%CONFIG_FILE%.bak" >nul
  echo Backup saved to config.bat.bak
  call "%CONFIG_FILE%"
  echo.
  echo Current values (press Enter to keep):
)

set /p INSTANCE_ID_IN=Enter EC2 Instance ID [%INSTANCE_ID%]: 
if not defined INSTANCE_ID_IN set INSTANCE_ID_IN=%INSTANCE_ID%
:VALIDATE_INSTANCE
if not defined INSTANCE_ID_IN (
  echo Instance ID is required.
  set /p INSTANCE_ID_IN=Enter EC2 Instance ID: 
  goto VALIDATE_INSTANCE
)

set /p AWS_REGION_IN=Enter AWS Region [%AWS_REGION%]: 
if not defined AWS_REGION_IN set AWS_REGION_IN=%AWS_REGION%
if not defined AWS_REGION_IN set AWS_REGION_IN=us-west-2

set /p KEY_FILE_IN=Path to SSH private key [%KEY_FILE%]: 
if not defined KEY_FILE_IN set KEY_FILE_IN=%KEY_FILE%

if not exist "%KEY_FILE_IN%" (
  echo WARNING: Key file not found now; ensure path is correct later.
)

set /p SERVER_USER_IN=SSH user (ubuntu/ec2-user) [%SERVER_USER%]: 
if not defined SERVER_USER_IN set SERVER_USER_IN=%SERVER_USER%
if not defined SERVER_USER_IN set SERVER_USER_IN=ubuntu

set /p VOTE_SCRIPT_IN=Server vote script path [/home/%SERVER_USER_IN%/vote_shutdown.sh]: 
if not defined VOTE_SCRIPT_IN set VOTE_SCRIPT_IN=/home/%SERVER_USER_IN%/vote_shutdown.sh

echo.
echo Enter team member IPs (blank to finish). Example: 203.0.113.10
set COUNT=0
for /l %%n in (1,1,50) do (
  set /p TMP_IP=DEV%%n_IP: 
  if not defined TMP_IP goto DONE_IP_LOOP
  set DEV%%n_IP=!TMP_IP!
  set /a COUNT+=1
)
:DONE_IP_LOOP

if %COUNT%==0 (
  echo No IPs entered. You should edit config later to add team IPs.
)

echo.
set /p YOUR_NAME_IN=Your display name [%YOUR_NAME%]: 
if not defined YOUR_NAME_IN set YOUR_NAME_IN=%YOUR_NAME%
if not defined YOUR_NAME_IN set YOUR_NAME_IN=Developer1

:CHOOSE_YOUR_IP
echo Select your IP from entered list (number) or enter custom value.
set IDX=0
for /f "tokens=1,2 delims==" %%A in ('set DEV[0-9]*_IP 2^>nul') do (
  set /a IDX+=1
  echo   !IDX!. %%B
  set IP_!IDX!=%%B
)
set /p CHOICE=Your IP selection or value: 
set YOUR_IP_IN=
if defined CHOICE (
  for /f "delims=0123456789" %%c in ("%CHOICE%") do set NONNUM=1
  if not defined NONNUM if defined IP_%CHOICE% set YOUR_IP_IN=!IP_%CHOICE%! 
)
if not defined YOUR_IP_IN set YOUR_IP_IN=%CHOICE%
if not defined YOUR_IP_IN (
  echo IP required.
  goto CHOOSE_YOUR_IP
)

echo.
echo Writing config.bat...
>"%CONFIG_FILE%" echo @echo off
>>"%CONFIG_FILE%" echo REM ============================================
>>"%CONFIG_FILE%" echo REM AWS EC2 QuorumStop - Configuration
>>"%CONFIG_FILE%" echo REM Generated by setup-wizard.bat on %date% %time%
>>"%CONFIG_FILE%" echo REM ============================================
>>"%CONFIG_FILE%" echo.
>>"%CONFIG_FILE%" echo REM AWS Configuration
>>"%CONFIG_FILE%" echo set INSTANCE_ID=%INSTANCE_ID_IN%
>>"%CONFIG_FILE%" echo set AWS_REGION=%AWS_REGION_IN%
>>"%CONFIG_FILE%" echo.
>>"%CONFIG_FILE%" echo REM Server Connection ^(Dynamic^)
>>"%CONFIG_FILE%" echo set SERVER_IP=0.0.0.0
>>"%CONFIG_FILE%" echo set KEY_FILE=%KEY_FILE_IN%
>>"%CONFIG_FILE%" echo.
>>"%CONFIG_FILE%" echo REM Team IP Mappings
for /f "tokens=1,2 delims==" %%A in ('set DEV[0-9]*_IP 2^>nul') do >>"%CONFIG_FILE%" echo set %%A=%%B
>>"%CONFIG_FILE%" echo.
>>"%CONFIG_FILE%" echo REM Current User Configuration
>>"%CONFIG_FILE%" echo set YOUR_NAME=%YOUR_NAME_IN%
>>"%CONFIG_FILE%" echo set YOUR_IP=%YOUR_IP_IN%
>>"%CONFIG_FILE%" echo.
>>"%CONFIG_FILE%" echo REM Server Configuration
>>"%CONFIG_FILE%" echo set SERVER_VOTE_SCRIPT=%VOTE_SCRIPT_IN%
>>"%CONFIG_FILE%" echo set SERVER_USER=%SERVER_USER_IN%
>>"%CONFIG_FILE%" echo.
>>"%CONFIG_FILE%" echo REM Display Configuration
>>"%CONFIG_FILE%" echo if "%%1"=="show" ^(
>>"%CONFIG_FILE%" echo   echo ============================================
>>"%CONFIG_FILE%" echo   echo AWS EC2 QuorumStop - Configuration
>>"%CONFIG_FILE%" echo   echo ============================================
>>"%CONFIG_FILE%" echo   echo Instance ID: %%INSTANCE_ID%%
>>"%CONFIG_FILE%" echo   echo Region: %%AWS_REGION%%
>>"%CONFIG_FILE%" echo   echo Server IP: %%SERVER_IP%%
>>"%CONFIG_FILE%" echo   echo SSH Key: %%KEY_FILE%%
>>"%CONFIG_FILE%" echo   echo User: %%SERVER_USER%%
>>"%CONFIG_FILE%" echo   echo.
>>"%CONFIG_FILE%" echo   echo Team IPs:
for /f "tokens=1,2 delims==" %%A in ('set DEV[0-9]*_IP 2^>nul') do >>"%CONFIG_FILE%" echo   echo     %%A=%%%%A%%
>>"%CONFIG_FILE%" echo   echo.
>>"%CONFIG_FILE%" echo   echo Current User: %%YOUR_NAME%% (%%YOUR_IP%%)
>>"%CONFIG_FILE%" echo ^)

echo.
echo config.bat written to scripts\config.bat
echo Next steps:
echo   1. Run scripts\test_aws.bat
echo   2. Run scripts\start_server.bat
echo   3. Install server vote script on EC2 (see docs)

exit /b 0
